version: '3.8'
services:
  karventer-api:
    build: ./backend
    container_name: karventer-api
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434/api/generate
      - DATABASE_URL=postgresql+psycopg://postgres:password@karventer-db:5432/karventer
    depends_on:
      - karventer-db
      - karventer-cache

  karventer-db:
    image: postgres:15-alpine
    container_name: karventer-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: karventer

  karventer-cache:
    image: redis:7-alpine
    container_name: karventer-cache

  karventer-frontend:
    build: ./frontend
    container_name: karventer-frontend
    ports:
      - "5173:5173"
    depends_on:
      - karventer-api