"""Market tablosuna sehir eklendi

Revision ID: 2897c3f210c0
Revises: 346e64778aa1
Create Date: 2026-04-07 17:07:07.350123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2897c3f210c0'
down_revision: Union[str, Sequence[str], None] = '346e64778aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('city', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markets', 'city')
    # ### end Alembic commands ###
