"""Market tablosuna sehir, ilce ve olcek eklendi

Revision ID: a7648aa514ea
Revises: 2897c3f210c0
Create Date: 2026-04-07 17:14:44.315399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7648aa514ea'
down_revision: Union[str, Sequence[str], None] = '2897c3f210c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('district', sa.String(length=50), nullable=True))
    op.add_column('markets', sa.Column('scale', sa.String(length=20), nullable=True))
    op.drop_column('markets', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('markets', 'scale')
    op.drop_column('markets', 'district')
    # ### end Alembic commands ###
